spring:
    application:
        name: admin-client
    boot:
        admin:
            client:
                url: http://localhost:8000
                username: admin
                password: admin
server:
    port: 8001

management:
    endpoints:
        web:
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: ALWAYS
logging:
    file: ./logs/admin-client.log  #添加开启admin的日志监控